### ISSUE TITLE
Adding Samba Users

### ISSUE THREAD

**Issue by deonthomasgy** [Elive/smb-admin#3]
- Adding some users to the "valid users" of smb-admin (editing a share), causes wrong extra " and spaces characters in the smb.conf file for this entry

_This bug needs confirming_

**Comment by TheTechRobo** [comment]
You say "some users", which users do you mean? Or are you saying "adding users"?

**Comment by deonthomasgy** [comment]
@TheTechRobo thanks for following up but it's been 8 years. this ticket can be closed!
